### ISSUE TITLE
[Crash] Tried to enter the world

### ISSUE THREAD

**Issue by DrSigma4164** [SuperMartijn642/ChunkLoaders#50] opened 2022-03-10 14:22 UTC
**Version Info**
- Minecraft, 1.16.5
- Chunk Loaders, 1.1.11

**Are you using OptiFine?: No

**Steps to Reproduce**
1)Tried to enter the world

**Crash report (~/logs/latest.log)**
crash - https://gist.github.com/4a0d1c313b69d54455a3cbfb153c99f2.git
latest - https://gist.github.com/e3c5f489950d5608188b58f6c2b5e830.git

**Comment by SuperMartijn642** [comment] 2022-03-10 14:39
The crash appears to be caused by Applied Energistics.

**Comment by DrSigma4164** [comment] 2022-03-10 22:10
I was told as follows:
> It's incompatible.
> The chunkloader mod is loading the chunk before the world has completed loading.
> Forge has it's own chunkloading API, which is compatible with AE2.
> Sorry, but we're not going to implement specific compatibility with this mod in 1.16.

Could you, if ae2 is installed in the modpack, use the API mentioned above?

**Comment by SuperMartijn642** [comment] 2022-03-11 17:55
Chunk Loaders is already using the API's provided.

The problem seems to come from this line:
https://github.com/SuperMartijn642/ChunkLoaders/blob/5cb2d4967b0e3e5a2e593d2fae2583cd4af890d6/src/main/java/com/supermartijn642/chunkloaders/ChunkLoaderUtil.java#L133
The line is part of loading code for Chunk Loaders' world capability. During loading, the `ChunkLoaderUtil$ChunkTracker#add` method ends up calling `World#setChunkForced` which also causes the chunk to load.

The issue seems to be a rare occurrence as it hasn't been reported before. I can also not reproduce the issue with just Chunk Loaders and Applied Energistics 2 installed.

I am working on redoing pretty much all of Chunk Loaders. I will not be fixing it right now, as this appears to be an uncommon issue and the code for it will be redone anyways.

**Comment by SuperMartijn642** [comment] 2022-07-12 16:06
The problem is fixed now in version 1.2.0 of Chunk Loaders.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2022-07-12 16:06 UTC
Labels: crash
