### ISSUE TITLE
[Bug] Chunkloader doens't work on botania

### ISSUE THREAD

**Issue by Parciwal** [SuperMartijn642/ChunkLoaders#15] opened 2021-04-18 10:49 UTC
**Version Info**
- Minecraft, 1.16.5
- Chunk Loaders, chunkloaders-1.1.6-mc1.16.5.jar

**Description of the Bug**
It doesn't load the Mana spreaders (they don't work)

**Steps to Reproduce**
1. install Chunk Loaders and botania
2. make an "automated" (with other mods or with a dispenser) Mana producing plant
3. use the Mana spreader to shoot the mana into a mana pool
4. install a chunkloade rin the chunk
5. note the amount of mana (you can see it with a wand of the forrest) and then leave the area so only the chunkloader loads the chunk

**Screenshots**
I'm not sure how to screenshot this

**Comment by SuperMartijn642** [comment] 2021-04-18 13:46
It seems to work fine when I test it.
https://youtu.be/N5UX63BHIA4
It also still works if I replace the full mana pool in the video with Endoflames and a stack of coal.

**Comment by Parciwal** [comment] 2021-04-18 15:45
I had it on a server and it didn't seem to work, but it could be that the problem is with the create mod. I used bohe for the automated mana production but the mana pools didn`t fill up

**Comment by SuperMartijn642** [comment] 2022-07-16 16:19
The way Chunk Loaders actually loads the chunks has changed in the 1.2.0 update. Combined with the fact that the issue seemed to be caused by something to do with Create, I will be closing the issue.
Please open a new issue with more details if the issue persists.

**Closed as completed by SuperMartijn642** 2022-07-16 16:19 UTC
Labels: bug
