### ISSUE TITLE
[Crash] Immediate crash when placing any chunkloader

### ISSUE THREAD

**Issue by jweispfenning** [SuperMartijn642/ChunkLoaders#48] opened 2022-01-29 16:54 UTC
**Version Info**
- Minecraft: 1.18.1
- Forge: 39.0.63
- Chunk Loaders: 1.1.8
- SuperMartijn642 Core Lib: 1.0.16
- SuperMartijn642 Config Lib: 1.0.9

**Steps to Reproduce**
1. Create Brand new world with only the above mods listed
2. Enter creative mode
3. Get any chunkloader block
4. Place chunkloader block
5. crash happens immediately after placing

**Crash report (~/logs/latest.log)**
[crash-2022-01-29_10.37.32-server.txt](https://github.com/SuperMartijn642/ChunkLoaders/files/7964148/crash-2022-01-29_10.37.32-server.txt)

[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/7964155/latest.log)

**Comment by jweispfenning** [comment] 2022-01-29 16:55
any guidance would be appreciated :)

**Comment by SuperMartijn642** [comment] 2022-01-29 18:24
This is caused by a change in Forge 39.0.45. Until I update Chunk Loaders, you can use a Forge version below 39.0.45.

**Comment by jweispfenning** [comment] 2022-01-29 20:16
Thank you for the response @SuperMartijn642 really appreciate it! That worked great! closing this now

**Comment by SuperMartijn642** [comment] 2022-01-29 20:33
Still something I will need to update, so I will leave it open so I don't forget about it

**Comment by SuperMartijn642** [comment] 2022-02-03 22:45
Ah nevermind, you need to use my core lib 1.0.16**a**. It has already been fixed in that version.

**Closed as completed by SuperMartijn642** 2022-02-03 22:45 UTC
Labels: crash
