### ISSUE TITLE
[Bug] Chunkloader causes world data to load too early

### ISSUE THREAD

**Issue by Darkere** [SuperMartijn642/ChunkLoaders#54] opened 2022-05-11 18:17 UTC
**Version Info**
- Minecraft, 1.18.2

**Description of the Bug**
The chunkloaders mod seems to cause the world data to be loaded too early. Early enough that the level itself is not loaded yet.
RS relies on reading the level, which causes it to entirely lose its stored data. 

**Steps to Reproduce**
chunkload RS system

User summed it up well over here: https://github.com/refinedmods/refinedstorage/issues/3299

I'm not sure if there is another way for us to read the world data to avoid this. But changing the load order seems a bit sketchy.

**Comment by SuperMartijn642** [comment] 2022-05-13 09:54
I believe is the same problem as #50.

The problem seems to come from this line:
https://github.com/SuperMartijn642/ChunkLoaders/blob/5cb2d4967b0e3e5a2e593d2fae2583cd4af890d6/src/main/java/com/supermartijn642/chunkloaders/ChunkLoaderUtil.java#L133
The line is part of the loading code for Chunk Loaders' world capability. During loading, the `ChunkLoaderUtil$ChunkTracker#add` method ends up calling `World#setChunkForced` which also causes the chunk to load.
This is not intentional behavior, but rather just a side effect of calling `World#setChunkForced` during world capability loading.

I don't have much time available to work on mods currently, so it might be a while before this gets addressed.

**Comment by SuperMartijn642** [comment] 2022-07-12 16:06
The problem is fixed now in version 1.2.0 of Chunk Loaders.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2022-07-12 16:06 UTC
Labels: bug
