### ISSUE TITLE
[Crash] Crashes when opening the overlay in the mod pack I added this to

### ISSUE THREAD

**Issue by Codyrays** [SuperMartijn642/ChunkLoaders#100] opened 2023-08-19 11:16 UTC
**Version Info**
- Minecraft, 1.20.1
- Chunk Loaders, 1

**Are you using OptiFine?:** No

**Steps to Reproduce**
Press the "View Chunk Loaders" keybind or right-clicking a placed chunk loader

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/12385716/latest.log)

**Comment by SuperMartijn642** [comment] 2023-08-19 13:32
This is caused by the combination of OptiFine and Iceberg. You'll have to update Iceberg.

Nothing to do with Chunk Loaders though, so I'll close the issue.

**Closed as completed by SuperMartijn642** 2023-08-19 13:32 UTC
Labels: crash
