### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by laserboy07** [SuperMartijn642/ChunkLoaders#82] opened 2023-04-21 11:35 UTC
**Version Info**
- Minecraft, 1.19.4
- Chunk Loaders, 1.2.3a-fabric-mc1.19

**Are you using OptiFine?:** no, but using sodium

**Steps to Reproduce**
whenever I put down a chunk loader and loaded a chunk, my FPS drops down instantly to around 0, and then the game crashes

**Crash report (~/logs/latest.log)**
Minecraft Exit Code Error: exit code -805306369

**Comment by SuperMartijn642** [comment] 2023-04-21 11:47
Please share the crash report.

**Comment by laserboy07** [comment] 2023-04-21 12:41
I'm sorry for bothering, but where can I find the report?
It's not in the crash-reports folder

**Comment by laserboy07** [comment] 2023-04-21 12:47
[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/11295816/latest.log)

**Comment by SuperMartijn642** [comment] 2023-04-22 16:36
Thank you for the log!

I cannot reproduce the issue. Even with all the mods shown in the log installed, when I place a chunk loader and load a chunk, everything works as expected.
The log also appears to be cut off (nothing you can do about that) and no error is shown.

Is there anything specific you do to reproduce this issue?

**Comment by laserboy07** [comment] 2023-04-22 16:53
Thanks for the quick answer!
I have just tried to do it again now, even when only using the mod, core and config lib and the fabric API, and it still acts the same.
I did nothing special for this crash to happen, as soon as I load a chunk and exit the chunkloader menu, it just happens.

**Comment by laserboy07** [comment] 2023-04-22 19:33
If it would help you, I will be able to share a video reproduction of the crash, as soon as I get home tomorrow

**Comment by laserboy07** [comment] 2023-04-23 15:20
https://user-images.githubusercontent.com/111233174/233848385-447f0576-8f34-4d9e-b189-1ac1e8d941bf.mp4

**Comment by laserboy07** [comment] 2023-04-23 15:32
Also, didn't record it, but it crashes after doing this for a few seconds

**Comment by SuperMartijn642** [comment] 2023-05-13 12:29
Should be fixed now in version 1.2.3b. Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2023-05-13 12:29 UTC
Labels: crash
