### ISSUE TITLE
[Crash] Crash the game on startup everytime after one successful trial, could be something related to optfine

### ISSUE THREAD

**Issue by NeonCao** [SuperMartijn642/ChunkLoaders#40] opened 2022-01-10 14:32 UTC
**Version Info**
- Minecraft, 1.18.1
- Chunk Loaders, 1.1.8
- Optfine, HD_U_H4

**Steps to Reproduce**
install the mod (with optfine), start the game, everything goes normal, close the game, and after that the game crash everytime on startup. no sure if its the issue with mod or optfine

**Crash report (~/logs/latest.log)**
[crash-2022-01-10_09.16.32-fml.txt](https://github.com/SuperMartijn642/ChunkLoaders/files/7839518/crash-2022-01-10_09.16.32-fml.txt)
[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/7839521/latest.log)

**Comment by NeonCao** [comment] 2022-01-10 15:24
a screenshot of the crash, in order if it would help with debugging. 
![image](https://user-images.githubusercontent.com/69925487/148791418-dcd6f17d-56e2-4386-9140-6b52e3bf70e6.png)

**Comment by SuperMartijn642** [comment] 2022-01-10 22:40
> install the mod (with optfine), start the game, everything goes normal, close the game, and after that the game crash everytime on startup

Minecraft doesn't crash when I try this.

`com.electronwill.nightconfig.core.io.ParsingException: Not enough data available`
This seems to be the cause of the crash. It's trying to read the config.
Could you delete the config file and see if the error still occurs?
Also, what Forge version are you using?

**Comment by NeonCao** [comment] 2022-01-12 01:14
the forge I'm using is 39.0.7.
the error is indeed caused by the config file, I unloaded the chunker loader mod and try relaunching the game and it still crashes, when I check the config folder I found about 30 config files from random mods are corrupted (shows the unsupported file type in VS coder). After I deleted all the corrupted config files the game runs normally. so I add the chunker loader mod back and everything goes normal until now. now sure why the config file was corrupted. I'll leave a new comment if the same thing happens again. Thank you so much for the fast response.

**Comment by SuperMartijn642** [comment] 2022-01-12 01:32
I believe this is an issue in Forge, however it only occurs rarely. Since it is hard to reproduce, Forge hasn't been able to fix it.

Anyways, glad things work again for you. Closing this as it doesn't seem to be caused by Chunk Loaders.

**Closed as completed by SuperMartijn642** 2022-01-12 01:32 UTC
Labels: crash
