### ISSUE TITLE
[Crash] Chunkloader and waystone mod crashes on 1.16.5

### ISSUE THREAD

**Issue by 162007** [SuperMartijn642/ChunkLoaders#57] opened 2022-07-14 14:40 UTC
**Version Info**
- Minecraft, 1.16.5
- Chunk Loaders, Chunk Loaders 1.2.0 for Forge 1.16

**Are you using OptiFine?:** no

**Steps to Reproduce**
1. Load world
2. Load chunk with the block
3. Use waystone 
4. crash

**Crash report (~/logs/latest.log)**
...
[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/9112724/latest.log)

**Comment by SuperMartijn642** [comment] 2022-07-14 19:47
I cannot reproduce the issue and the log doesn't show any crash nor anything to do with Chunk Loaders or Waystones really.

You seem to be using quite a lot of mods. Can you reproduce the issue with just Chunk Loaders, Waystones, and their dependencies?
And do you have more specific instructions on how to reproduce the issue? 'Use waystone' is rather unclear.

**Comment by 162007** [comment] 2022-07-15 11:58
Okay sure, let me make it more clear, 
1. Load up a world with chunk loader and waystones mod
2. Place a waystone 
3. Place a chunk loader and load a chunk
4. Use a waystone
5. Game freezes and can't do anything

**Comment by SuperMartijn642** [comment] 2022-07-15 16:00
I cannot reproduce the issue, waystones work just fine. Can you reproduce the issue with just Chunk Loaders, Waystones, and their dependencies?

What do you mean by 'Use a waystone', just opening the gui, traveling to some other waystone? Should I place the waystone anywhere specific like far away from the chunk loader or inside the loaded area?

Not sure why you closed the issue as not planned 🤔

**Comment by SuperMartijn642** [comment] 2022-08-04 13:26
Closing this as there hasn't been a response.

**Closed as completed by SuperMartijn642** 2022-08-04 13:26 UTC
Labels: crash
