### ISSUE TITLE
[Crash] A server crash with waystones mod

### ISSUE THREAD

**Issue by MundM2007** [SuperMartijn642/ChunkLoaders#33] opened 2021-12-23 12:44 UTC
**Version Info**
- Minecraft, 1.16.5, forge 36.2.20, server
- Chunk Loaders, v1.1.7
- Additional mod: waystones v7.6.4
- maybe other mods cause this aswell if you want to fully install the modpack i'm using the modpack "Ultimate Progression" v0.5.0

**Steps to Reproduce**
1. install server with chunk loaders and waystones
2. place some waystones in the same chunk as the chunk loader (that loads these chunks)
3. sometimes when you restart the server, it crashes

**Crash report (~/logs/latest.log)**
[crash-reports_crash-2021-12-23_11.18.43-server.txt](https://github.com/SuperMartijn642/ChunkLoaders/files/7769310/crash-reports_crash-2021-12-23_11.18.43-server.txt)

**Comment by SuperMartijn642** [comment] 2022-07-12 16:08
The problem is fixed now in version 1.2.0 of Chunk Loaders.
Thank you for reporting the issue!

**Closed as completed by SuperMartijn642** 2022-07-12 16:08 UTC
Labels: crash
