### ISSUE TITLE
[Question] "Chunk Not Loaded" on Server

### ISSUE THREAD

**Issue by Splatracer** [SuperMartijn642/ChunkLoaders#62] opened 2022-08-03 18:39 UTC
So a friend and I have been playing on our own server for a few days now, with a few mods including this Chunkloader mod. Today we're at the point where we wanted to use the chunkloaders for a farm. I crafted the basic one, placed it down, and all chunks appeared as "not loaded", and I couldn't change it either. But when I try to craft one in a singleplayer world (same mods and everything), it works as intended. Any idea what it could be?

Thanks in advance.

**Comment by SuperMartijn642** [comment] 2022-08-04 13:25
This sounds like just a bug with Chunk Loaders. What version of Minecraft and Chunk Loaders are you using?

For now, if you have OP permissions and hold shift, you can change anyone's chunk loaders. Might work for you in this case, although not completely sure.

**Comment by Splatracer** [comment] 2022-08-04 14:20
We are playing on 1.18.2 (Forge version 40.1.69), Chunkloaders 1.2.0c, ConfigLib version 1.1.6 and CoreLib version 1.0.19

I made sure that on both client-side (for me and my friend) and server-side all mods have the same version, so I find it weird it works in singleplayer but not multiplayer. But I will try that out with what you said about OP

**Comment by SuperMartijn642** [comment] 2022-08-04 14:43
I can't reproduce the issue. Both with a server in online and offline mode, I can place a basic chunk loader and load the chunks from the gui.
Does it show it your username as the owner inside the chunk loader's gui?
Is there anything else about your server setup you think might be relevant?

**Comment by Splatracer** [comment] 2022-08-04 15:12
No, my name didn't show within the GUI. It only shows the chunks in range. And I set the server up like I normally would with a modded server, and I never had problems before

**Comment by Splatracer** [comment] 2022-08-04 15:18
So I just joined the server again to test something and also make a screenshot for you, but now it works and my name shows in the GUI. I guess the problem somehow fixed itself

Well, thanks for the help anyways!

**Comment by SuperMartijn642** [comment] 2022-08-04 17:04
Okay, glad it somehow fixed itself.
I will close the issue then. Let me know if the issue occurs again 🙂

**Closed as completed by SuperMartijn642** 2022-08-04 17:04 UTC
Labels: question
